# debux-stubs - fork for use with shadow-cljs

shadow-cljs does not allow for dependencies to be exchanged for different build targts, or at least I did not figure out how to do it.
Also I do prefer to explicitly express different functionality.

With this fork I simply renamed the debux namespace to debux-stubs for all stubs intendend for production builds.

That way one can use shadow-cljs' :ns-aliases feature to switch between the two libraries.

`:release    {:build-options {:ns-aliases {debux.cs.core debux-stubs.cs.core}}}`

# debux-stubs
# Debux
:source-language: clojure
:sectnums:

* `debux-stubs` library is the production version of `debux`
(link:https://github.com/philoskim/debux[]) library.

* Refer to link:https://github.com/philoskim/debux#two-libraries[Two Libraries] section
  for the relationship between `debux` and `debux-stubs` libraries.


## Installation

* To include `debux-stubs` in your project, simply add the following to your *project.clj*
  dependencies.

[listing]
----
[philoskim/debux-stubs "0.7.9"]
----


## License

Copyright © 2018--2020 Young Tae Kim

Distributed under the Eclipse Public License either version 1.0 or any later version.
